name: kofe_vkusno
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.1.0
  flutter_svg: 1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - resources/icons/menu_icon.svg
    - resources/images/app_bar_logo.png
    - resources/translations/

  fonts:
    - family: Pacifico
      fonts:
        - asset: resources/fonts/Pacifico-Regular.ttf
